# Generated by Django 2.1.7 on 2019-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190323_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
