# Generated by Django 2.1.7 on 2019-03-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190323_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopping_cart',
        ),
    ]
