# Generated by Django 2.1.7 on 2019-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется')], default='Принят в обработку', max_length=100),
        ),
    ]
