# Generated by Django 2.1.7 on 2019-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190330_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Оплачен', 'Оплачен'), ('Выполняется', 'Выполняется')], default='Принят в обработку', max_length=100),
        ),
    ]
